### ISSUE TITLE
Enhancement: option to allow more than 5 items per row

### ISSUE THREAD

**Issue by petersem** [plugsy/core#21]
This will help to display on a single page when there are more containers. (i run 70-80)

**Comment by Inlustra** [comment]
I think this will tie in with the dark theme actually! I intend to let people inject any CSS they'd like! I'll bump this up the priority list for sure!

**Comment by petersem** [comment]
I love this, especially as i was just about to write my own node-based version (and now don't have to. Although i may do it for fun anyhow) :)

Im still not sure how feasible it is for me though. As you can see, real estate is lacking and i still have lots of containers to add (not to mention ones on other machines, via your agent)
[so far](https://imgur.com/a/jKPUXeX)

**Comment by Inlustra** [comment]
I see! The best suggestion I have for you is to use the children/parents feature to hide all of the DBs under their respective parent (So that when you hover the item, you'll see the DB appear) Doing this will also show the service as down if any of children containers are also down.

You can see an example of this in the video in the README

There's a section on it in the README too

**Comment by petersem** [comment]
Good idea. I will re-jig to display that way. Thanks

**Comment by Inlustra** [comment]
Available in v4! See theming:
https://github.com/plugsy/core/blob/main/docs/theming.md

**Comment by petersem** [comment]
thanks.. was able to change padding values and now fits nicely on the screen in portrait
